### ISSUE TITLE
Tracking Roadmap

### ISSUE THREAD

**Issue by Durant35** [Durant35/precision-tracking#1]
- [ ] 如何提出一个更接近物体实际运动的预测模型；
- [ ] 如何提出一个鲁棒的观测模型对观测量进行修饰；
- [ ] 一个快速、有效的方法解决当前观测量与系统追踪器的关联问题。

**Comment by Durant35** [comment]
## Apollo's HM Tracking
- [ ] [MinBox 障碍物边框构建===>对观测量进行简单修饰](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/3d_obstacle_perception_cn.md#minbox-%E9%9A%9C%E7%A2%8D%E7%89%A9%E8%BE%B9%E6%A1%86%E6%9E%84%E5%BB%BA)
- [ ] [观察冗余以确保更鲁棒的观测模型](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/3d_obstacle_perception_cn.md#%E6%A3%80%E6%B5%8B%E8%B7%9F%E8%B8%AA%E5%85%B3%E8%81%94detection-to-track-association)
- [ ] [匈牙利算法高效完成检测跟踪关联（Detection-to-Track Association）](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/3d_obstacle_perception_cn.md#%E6%A3%80%E6%B5%8B%E8%B7%9F%E8%B8%AA%E5%85%B3%E8%81%94detection-to-track-association)
- [ ] [ 鲁棒卡尔曼滤波器来利用恒定速度运动模型来预测&更新追踪物体的运动状态](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/3d_obstacle_perception_cn.md#%E6%A3%80%E6%B5%8B%E8%B7%9F%E8%B8%AA%E5%85%B3%E8%81%94detection-to-track-association)

**Comment by Durant35** [comment]
## 可以在数据关联时考虑**观测<-->跟踪器**分类信息
> Azim A, Aycard O. Detection, classification and tracking of moving objects in a 3D environment[C]//Intelligent Vehicles Symposium (IV), 2012 IEEE. IEEE, 2012: 802-807.

![image](https://user-images.githubusercontent.com/6770853/37451805-b1ee590e-286d-11e8-9cbd-c6b606fafe79.png)
![image](https://user-images.githubusercontent.com/6770853/37451843-d0b3254a-286d-11e8-91c6-10ab69bdf62c.png)
